from iptfw.iptables import parse_rules


SAVE = """# Generated by iptables-save
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
[10:800] -A PREROUTING -p tcp -s 203.0.113.10/32 --dport 2222 -m comment --comment iptfw:abc -j DNAT --to-destination 192.168.1.20:22
[100:9000] -A POSTROUTING -s 192.168.1.0/24 -j MASQUERADE
COMMIT
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
[10:800] -A FORWARD -p tcp -d 192.168.1.20 --dport 22 -m comment --comment iptfw:abc -j ACCEPT
[4:200] -A INPUT -p udp --dport 53 -j ACCEPT
[1:40] -A INPUT -s 198.51.100.10/32 -j DROP
COMMIT
"""


def test_parse_and_classify_rules():
    rules = parse_rules(SAVE, [])
    assert len(rules) == 5
    dnat = rules[0]
    assert dnat.table == "nat"
    assert dnat.chain == "PREROUTING"
    assert dnat.rule_type == "DNAT / port forwarding"
    assert dnat.protocol == "tcp"
    assert dnat.source_ip == "203.0.113.10/32"
    assert dnat.destination_port == "2222"
    assert dnat.forwarded_ip == "192.168.1.20"
    assert dnat.forwarded_port == "22"
    assert dnat.managed is True


def test_filter_verdicts():
    rules = parse_rules(SAVE, [])
    assert rules[-2].rule_type == "ACCEPT"
    assert rules[-1].rule_type == "DROP"
